import { boolean, index, jsonb, pgTable, text, timestamp } from 'drizzle-orm/pg-core'

/**
 * Tool table — globally shared, visible to all users
 *
 * Previously stored in filesystem / localStorage, now migrated to database for multi-user sharing.
 */
export const tools = pgTable(
  'tools',
  {
    id: text('id').primaryKey(),
    /** Tool name */
    name: text('name').notNull(),
    /** Tool description */
    description: text('description').notNull().default(''),
    /** Version number, format V1.0.YYYYMMDD */
    version: text('version').notNull().default('V1.0.0'),
    /** Tool code (JavaScript) */
    code: text('code'),
    /** Parameter JSON Schema: { type, properties, required } */
    parameters: jsonb('parameters'),
    /** Preset parameter values */
    presetParams: jsonb('preset_params'),
    /** Category tag, e.g. "AI Generated", "Official" */
    category: text('category'),
    /** Source author */
    author: text('author'),
    /** Code language, default javascript */
    language: text('language').notNull().default('javascript'),
    /** Source: installed / official */
    source: text('source').notNull().default('installed'),
    /** External URL (official tool detail page, etc.) */
    url: text('url'),
    /** K8S deployment info JSONB: { status, endpoint, nodePort, deployedAt, errorMessage } */
    deploy: jsonb('deploy'),
    /** Env vars (secret param values), injected into Pod env on deployment */
    envVars: jsonb('env_vars'),
    /** API doc (Markdown), auto-generated by AI, injected as tool description for LLM during SOP calls */
    apiDoc: text('api_doc'),
    /** Required system connection type JSONB: { type: 'database', dbType?: 'mysql' }; new instances only match same-type connections */
    connectorType: jsonb('connector_type'),
    /**
     * Whether this tool needs a per-SOP-execution MinIO workspace mounted
     * at /workspace. Tools with this flag bypass the warm pool: deploy is
     * deferred until SOP execution time so the rclone sidecar can scope
     * its mount to the running execution's prefix.
     */
    needsFileMount: boolean('needs_file_mount').notNull().default(false),
    /** SHA-256 hex digest of the .cmtool zip bytes */
    packageSha256: text('package_sha256'),
    /** Creator user ID */
    createdBy: text('created_by').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    categoryIdx: index('tools_category_idx').on(table.category),
    createdByIdx: index('tools_created_by_idx').on(table.createdBy),
  })
)
