import { index, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core'
import { user } from '../schema'
import { toolDevSessions } from './tool-dev-sessions'
import { toolInstances } from './tool-instances'

/**
 * Per-invocation tool execution record. Used by /api/employee/tool-execution/[execId]/files
 * routes to authorize file IO access (the execId in URL must belong to a session/instance
 * owned by the requesting user).
 *
 * `id` is a content-safe string (e.g. "test_20260528_a1b2c3"), generated by
 * lib/core/execution-id.ts. NOT a UUID — embeds a date prefix for io path layering.
 *
 * Note: `userId` is `text` to match `user.id` (better-auth uses text PKs).
 * `instanceId` is `text` to match `tool_instances.id`. `sessionId` is `uuid`
 * to match `tool_dev_sessions.id`.
 *
 * Refs spec 2026-05-28-cross-platform-nfs-volume-design.md §5.4 + §9.5.
 */
export const toolExecutions = pgTable(
  'tool_executions',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    sessionId: uuid('session_id').references(() => toolDevSessions.id, {
      onDelete: 'set null',
    }),
    instanceId: text('instance_id').references(() => toolInstances.id, {
      onDelete: 'set null',
    }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    byUser: index('tool_executions_user_idx').on(t.userId, t.createdAt),
    bySession: index('tool_executions_session_idx').on(t.sessionId),
    byInstance: index('tool_executions_instance_idx').on(t.instanceId),
  })
)

export type ToolExecution = typeof toolExecutions.$inferSelect
export type NewToolExecution = typeof toolExecutions.$inferInsert
