import { channelSessions, db } from '@crewmeld/db'
import { createLogger } from '@crewmeld/logger'
import { eq } from 'drizzle-orm'
import { getBaseUrl } from '@/lib/core/utils/urls'
import { generateApprovalToken } from '@/lib/human-employees/approval-token'
import { buildNotificationContent } from '@/lib/human-employees/notification-content'
import {
  dispatchApprovalToChannelUser,
  dispatchNotification,
} from '@/lib/human-employees/notification-dispatcher'
import type { NotificationJobPayload } from '@/types/sop'

const logger = createLogger('SopNotificationWorker')

/**
 * Resolve the requester's real channel-native delivery id + id type for the
 * requester_self approval card, from channel_sessions (keyed by conversation id).
 *
 * Mirrors sop-completion-notifier — the deliverable id is NOT the platform user
 * id in _meta.userId. For Feishu, channel_sessions.externalUserId holds the
 * (non-deliverable) user_id, while externalSessionId holds the chat_id — the
 * p2p chat for a DM, which is what the send API actually accepts. Other channels
 * store their native user id in externalUserId.
 *
 * @returns resolved delivery target, or null when no usable id is found.
 */
async function resolveRequesterDeliverable(
  conversationId: string,
  channel: string
): Promise<{ receiveId: string; receiveIdType: string } | null> {
  const [session] = await db
    .select({
      externalUserId: channelSessions.externalUserId,
      externalSessionId: channelSessions.externalSessionId,
    })
    .from(channelSessions)
    .where(eq(channelSessions.conversationId, conversationId))
    .limit(1)

  if (!session) return null

  if (channel === 'feishu') {
    // Feishu's deliverable id is the chat_id (externalSessionId). externalUserId
    // is the feishu user_id, which the send API does not accept as an open_id —
    // so if there's no chat_id, return null and let the caller fall back rather
    // than send to an id Feishu can't resolve.
    if (!session.externalSessionId) return null
    return { receiveId: session.externalSessionId, receiveIdType: 'chat_id' }
  }

  // Other channels address the user by their native id stored in externalUserId.
  if (!session.externalUserId) return null
  return { receiveId: session.externalUserId, receiveIdType: 'user_id' }
}

/**
 * SOP Notification Delivery Worker
 *
 * 1. Use the approval token from payload (inline-generated by node executor)
 * 2. Build approval URL + notification text
 * 3. Deliver notification via dispatcher
 */
export async function processNotification(payload: NotificationJobPayload): Promise<void> {
  const { contextData } = payload

  logger.info('Starting notification delivery', {
    executionId: payload.executionId,
    pauseId: contextData.pauseId,
    recipientId: payload.recipientId,
    messageTemplate: payload.messageTemplate,
  })

  try {
    // Use the pre-generated token from node executor; fall back to generating one if empty (backward compat)
    let token = payload.approvalToken
    if (!token) {
      const generated = await generateApprovalToken(contextData.pauseId)
      token = generated.token
    }

    // Prefer baseUrl captured from request headers at SOP trigger time (dynamic domain)
    // Then APP_BASE_URL (server-side only, modifiable at runtime)
    // NEXT_PUBLIC_APP_URL is inlined at build time and cannot be changed at runtime
    const baseUrl = contextData.baseUrl || getBaseUrl()

    const content = buildNotificationContent(
      {
        sopName: contextData.sopName,
        nodeName: contextData.nodeName,
        executionId: payload.executionId,
        aiSummary: contextData.aiSummary,
        deadline: contextData.deadline,
        previousNodeResult: contextData.previousNodeResult,
        previousNodeName: contextData.previousNodeName,
      },
      baseUrl,
      contextData.pauseId,
      token,
      contextData.userLanguage ?? 'zh'
    )

    const approvalContent = {
      subject: content.subject,
      body: content.body,
      pauseId: contextData.pauseId,
      sopName: contextData.sopName,
      nodeName: contextData.nodeName,
      aiSummary: contextData.aiSummary,
      deadline: contextData.deadline,
      previousNodeResult: contextData.previousNodeResult,
      previousNodeName: contextData.previousNodeName,
      approvalPageUrl: content.approvalUrl,
      approveUrl: content.approveUrl,
      rejectUrl: content.rejectUrl,
      senderName: contextData.senderName,
      senderEmail: contextData.senderEmail,
      language: contextData.userLanguage,
    }

    // approverSource='requester_leader': deliver to the requester's leader on
    // their channel. On failure (no leader / invalid leader id / send error),
    // fall back to the configured assignee below.
    if (
      payload.approverSource === 'requester_leader' &&
      contextData.requesterChannel &&
      contextData.leaderId
    ) {
      const leaderResult = await dispatchApprovalToChannelUser(
        contextData.requesterChannel,
        contextData.leaderId,
        approvalContent,
        payload.sourceEmployeeId
      )
      if (leaderResult) {
        logger.info('Approval routed to requester leader', {
          pauseId: contextData.pauseId,
          channel: contextData.requesterChannel,
          status: leaderResult.status,
        })
        return
      }
      logger.info('Leader routing unavailable, falling back to configured assignee', {
        pauseId: contextData.pauseId,
        recipientId: payload.recipientId,
      })
    }

    // approverSource='requester_self': deliver back to the requester on their own
    // channel. Resolve the real channel-native id (e.g. feishu open_id) from
    // channel_sessions via the conversation id — the platform user id in
    // requesterUserId is NOT what the channel send API accepts. On failure (no
    // session / invalid id / send error), fall back to the configured assignee.
    if (payload.approverSource === 'requester_self' && contextData.requesterChannel) {
      const deliverable = contextData.conversationId
        ? await resolveRequesterDeliverable(contextData.conversationId, contextData.requesterChannel)
        : null
      // Fall back to the raw requesterUserId only when no session was found (keeps
      // prior behavior for channels/records without a channel_session).
      const toUser = deliverable?.receiveId ?? contextData.requesterUserId
      const receiveIdType = deliverable?.receiveIdType ?? 'user_id'

      if (toUser) {
        const requesterResult = await dispatchApprovalToChannelUser(
          contextData.requesterChannel,
          toUser,
          approvalContent,
          payload.sourceEmployeeId,
          receiveIdType,
          // The requester's chat belongs to the digital employee's own bot — use
          // that bound connection, not the global notification bot (a different
          // app that isn't a member of this chat).
          true
        )
        if (requesterResult) {
          logger.info('Approval routed to requester', {
            pauseId: contextData.pauseId,
            channel: contextData.requesterChannel,
            receiveIdType,
            resolvedFromSession: !!deliverable,
            status: requesterResult.status,
          })
          return
        }
      }
      logger.info('Requester routing unavailable, falling back to configured assignee', {
        pauseId: contextData.pauseId,
        recipientId: payload.recipientId,
        hadSession: !!deliverable,
      })
    }

    const results = await dispatchNotification(
      payload.recipientId,
      approvalContent,
      payload.notifyMethod,
      payload.sourceEmployeeId
    )

    logger.info('Notification delivery completed', {
      pauseId: contextData.pauseId,
      recipientId: payload.recipientId,
      approvalUrl: content.approvalUrl,
      results: results.map((r: { contactType: string; status: string; message: string }) => ({
        type: r.contactType,
        status: r.status,
        message: r.message,
      })),
    })
  } catch (error) {
    logger.error('Notification delivery failed (non-blocking for SOP execution)', {
      executionId: payload.executionId,
      pauseId: contextData.pauseId,
      recipientId: payload.recipientId,
      error: error instanceof Error ? error.message : String(error),
    })
  }
}
