import { createLogger } from '@crewmeld/logger'
import { getBaseUrl } from '@/lib/core/utils/urls'
import { generateApprovalToken } from '@/lib/human-employees/approval-token'
import { buildNotificationContent } from '@/lib/human-employees/notification-content'
import {
  dispatchApprovalToChannelUser,
  dispatchNotification,
} from '@/lib/human-employees/notification-dispatcher'
import type { NotificationJobPayload } from '@/types/sop'

const logger = createLogger('SopNotificationWorker')

/**
 * SOP Notification Delivery Worker
 *
 * 1. Use the approval token from payload (inline-generated by node executor)
 * 2. Build approval URL + notification text
 * 3. Deliver notification via dispatcher
 */
export async function processNotification(payload: NotificationJobPayload): Promise<void> {
  const { contextData } = payload

  logger.info('Starting notification delivery', {
    executionId: payload.executionId,
    pauseId: contextData.pauseId,
    recipientId: payload.recipientId,
    messageTemplate: payload.messageTemplate,
  })

  try {
    // Use the pre-generated token from node executor; fall back to generating one if empty (backward compat)
    let token = payload.approvalToken
    if (!token) {
      const generated = await generateApprovalToken(contextData.pauseId)
      token = generated.token
    }

    // Prefer baseUrl captured from request headers at SOP trigger time (dynamic domain)
    // Then APP_BASE_URL (server-side only, modifiable at runtime)
    // NEXT_PUBLIC_APP_URL is inlined at build time and cannot be changed at runtime
    const baseUrl = contextData.baseUrl || getBaseUrl()

    const content = buildNotificationContent(
      {
        sopName: contextData.sopName,
        nodeName: contextData.nodeName,
        executionId: payload.executionId,
        aiSummary: contextData.aiSummary,
        deadline: contextData.deadline,
        previousNodeResult: contextData.previousNodeResult,
        previousNodeName: contextData.previousNodeName,
      },
      baseUrl,
      contextData.pauseId,
      token,
      contextData.userLanguage ?? 'zh'
    )

    const approvalContent = {
      subject: content.subject,
      body: content.body,
      pauseId: contextData.pauseId,
      sopName: contextData.sopName,
      nodeName: contextData.nodeName,
      aiSummary: contextData.aiSummary,
      deadline: contextData.deadline,
      previousNodeResult: contextData.previousNodeResult,
      previousNodeName: contextData.previousNodeName,
      approvalPageUrl: content.approvalUrl,
      approveUrl: content.approveUrl,
      rejectUrl: content.rejectUrl,
      senderName: contextData.senderName,
      senderEmail: contextData.senderEmail,
      language: contextData.userLanguage,
    }

    // approverSource='requester_leader': deliver to the requester's leader on
    // their channel. On failure (no leader / invalid leader id / send error),
    // fall back to the configured assignee below.
    if (
      payload.approverSource === 'requester_leader' &&
      contextData.requesterChannel &&
      contextData.leaderId
    ) {
      const leaderResult = await dispatchApprovalToChannelUser(
        contextData.requesterChannel,
        contextData.leaderId,
        approvalContent,
        payload.sourceEmployeeId
      )
      if (leaderResult) {
        logger.info('Approval routed to requester leader', {
          pauseId: contextData.pauseId,
          channel: contextData.requesterChannel,
          status: leaderResult.status,
        })
        return
      }
      logger.info('Leader routing unavailable, falling back to configured assignee', {
        pauseId: contextData.pauseId,
        recipientId: payload.recipientId,
      })
    }

    const results = await dispatchNotification(
      payload.recipientId,
      approvalContent,
      payload.notifyMethod,
      payload.sourceEmployeeId
    )

    logger.info('Notification delivery completed', {
      pauseId: contextData.pauseId,
      recipientId: payload.recipientId,
      approvalUrl: content.approvalUrl,
      results: results.map((r: { contactType: string; status: string; message: string }) => ({
        type: r.contactType,
        status: r.status,
        message: r.message,
      })),
    })
  } catch (error) {
    logger.error('Notification delivery failed (non-blocking for SOP execution)', {
      executionId: payload.executionId,
      pauseId: contextData.pauseId,
      recipientId: payload.recipientId,
      error: error instanceof Error ? error.message : String(error),
    })
  }
}
