import { AliyunIcon, AnthropicIcon, BaiduIcon, MoonshotIcon, ZhipuIcon } from '@/components/icons'
import type { ProviderDefinition } from '@/providers/models/types'

/** Provider definitions for coding-specialized LLM providers. */
export const codingProviders: Record<string, ProviderDefinition> = {
  'kimi-coding': {
    id: 'kimi-coding',
    name: 'Kimi 编程',
    description: '月之暗面 Kimi 编程模型（OpenAI 兼容协议）',
    defaultModel: 'kimi-for-coding',
    modelPatterns: [/^kimi/, /^moonshot/],
    icon: MoonshotIcon,
    category: 'coding',
    codingProtocol: 'openai-compatible',
    defaultEndpoint: 'https://api.kimi.com/coding/v1',
    capabilities: { toolUsageControl: true },
    models: [
      { id: 'kimi-for-coding', pricing: { input: 0, output: 0, updatedAt: '2026-07-27' }, capabilities: {} },
      { id: 'kimi-for-coding-highspeed', pricing: { input: 0, output: 0, updatedAt: '2026-07-27' }, capabilities: {} },
    ],
  },
  'qianfan-coding': {
    id: 'qianfan-coding',
    name: '千帆编程',
    description: '百度千帆编程模型',
    defaultModel: 'qianfan-code-latest',
    modelPatterns: [/^qianfan-code/],
    icon: BaiduIcon,
    category: 'coding',
    codingProtocol: 'openai-compatible',
    defaultEndpoint: 'https://qianfan.baidubce.com/v2/coding',
    capabilities: { toolUsageControl: true },
    models: [
      { id: 'qianfan-code-latest', pricing: { input: 0, output: 0, updatedAt: '2026-05-26' }, capabilities: {} },
    ],
  },
  'qwen-coding': {
    id: 'qwen-coding',
    name: '通义编程',
    description: '阿里云通义编程模型（Qwen Coder）',
    defaultModel: 'qwen3-coder-plus',
    modelPatterns: [/^qwen-code/, /^qwen.*coder/, /^qwen3/],
    icon: AliyunIcon,
    category: 'coding',
    codingProtocol: 'openai-compatible',
    defaultEndpoint: 'https://coding.dashscope.aliyuncs.com/v1',
    capabilities: { toolUsageControl: true },
    models: [
      { id: 'qwen3-coder-plus', pricing: { input: 0, output: 0, updatedAt: '2026-07-27' }, capabilities: {} },
      { id: 'qwen3-coder-next', pricing: { input: 0, output: 0, updatedAt: '2026-07-27' }, capabilities: {} },
    ],
  },
  'zhipu-coding': {
    id: 'zhipu-coding',
    name: '智谱 GLM 编程',
    description: '智谱 GLM Coding 模型（OpenAI 兼容协议）',
    defaultModel: 'glm-5.2',
    modelPatterns: [/^glm/i],
    icon: ZhipuIcon,
    category: 'coding',
    codingProtocol: 'openai-compatible',
    defaultEndpoint: 'https://open.bigmodel.cn/api/paas/v4/',
    capabilities: { toolUsageControl: true },
    models: [
      { id: 'glm-5.2', pricing: { input: 0, output: 0, updatedAt: '2026-07-24' }, capabilities: {} },
      { id: 'GLM-5', pricing: { input: 0, output: 0, updatedAt: '2026-07-24' }, capabilities: {} },
      { id: 'glm-4.7', pricing: { input: 0, output: 0, updatedAt: '2026-07-24' }, capabilities: {} },
    ],
  },
  'claude-coding': {
    id: 'claude-coding',
    name: 'Claude 编程',
    description: 'Claude 编程模型',
    defaultModel: 'claude-4-sonnet',
    modelPatterns: [/^claude/],
    icon: AnthropicIcon,
    category: 'coding',
    codingProtocol: 'anthropic',
    defaultEndpoint: 'https://api.anthropic.com/v1',
    capabilities: { toolUsageControl: true },
    models: [
      { id: 'claude-4-sonnet', pricing: { input: 0, output: 0, updatedAt: '2026-05-26' }, capabilities: {} },
      { id: 'claude-4-opus', pricing: { input: 0, output: 0, updatedAt: '2026-05-26' }, capabilities: {} },
      { id: 'claude-3-5-sonnet-20241022', pricing: { input: 0, output: 0, updatedAt: '2026-05-26' }, capabilities: {} },
    ],
  },
}
